import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { NextUiProvider } from "@/components/nextprovider";
import Appbar from "@/components/navbar";
import AuthSessionProvider from "@/components/auth-session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthSessionProvider>
        <body className={inter.className}>
          <div className="">
            <Appbar />
          </div>
          <div className="flex-grow flex items-center justify-center">
            <NextUiProvider>{children}</NextUiProvider>
          </div>
        </body>
      </AuthSessionProvider>
    </html>
  );
}
